id2industries_dict = {
    "000": "合計",
    "C": "鉱業、採石業、砂利採取業",
    "E": "製造業",
    "090": "食料品製造業",
    "091": "畜産食料品製造業",
    "092": "水産食料品製造業",
    "093": "精穀・製粉業",
    "099": "その他の食料品製造業",
    "100": "飲料・たばこ・飼料製造業",
    "101": "清涼飲料・酒類・茶・たばこ製造業",
    "102": "飼料・有機質肥料製造業",
    "110": "繊維工業",
    "111": "製糸，紡績，ねん糸等製造業",
    "112": "織物・ニット生地製造業",
    "113": "染色整理業",
    "114": "その他の繊維工業",
    "115": "織物・ニット製衣服製造業",
    "119": "身の回り品・その他の繊維製品製造業",
    "120": "木材・木製品製造業（家具を除く）",
    "121": "製材・合板製造業",
    "129": "その他の木製品製造業（家具を除く）",
    "130": "家具・装備品製造業",
    "140": "パルプ・紙・紙加工品製造業",
    "141": "パルプ・紙製造業",
    "142": "紙加工品製造業",
    "150": "印刷・同関連業",
    "160": "化学工業",
    "161": "化学肥料・無機化学工業製品製造業",
    "162": "有機化学工業製品製造業",
    "163": "油脂加工製品・石けん・合成洗剤・界面活性剤・塗料製造業",
    "164": "医薬品製造業",
    "169": "その他の化学工業製品製造業",
    "170": "石油製品・石炭製品製造業",
    "171": "石油精製業",
    "179": "その他の石油製品・石炭製品製造業",
    "180": "プラスチック製品製造業",
    "190": "ゴム製品製造業",
    "191": "タイヤ・チューブ製造業",
    "199": "その他のゴム製品製造業",
    "200": "なめし革・同製品・毛皮製造業",
    "210": "窯業・土石製品製造業",
    "211": "ガラス・同製品製造業",
    "212": "セメント・同製品製造業",
    "219": "その他の窯業・土石製品製造業",
    "220": "鉄鋼業",
    "221": "銑鉄・粗鋼・鋼材製造業",
    "222": "鋳鍛造品・その他の鉄鋼製品製造業",
    "230": "非鉄金属製造業",
    "231": "非鉄金属製錬・精製業",
    "232": "非鉄金属加工品製造業",
    "240": "金属製品製造業",
    "241": "建設用・建築用金属製品製造業",
    "249": "その他の金属製品製造業",
    "250": "はん用機械器具製造業",
    "251": "ボイラ・原動機製造業",
    "252": "ポンプ・圧縮機器製造業",
    "253": "一般産業用機械・装置製造業",
    "259": "その他のはん用機械・同部品製造業",
    "260": "生産用機械器具製造業",
    "261": "金属加工機械製造業",
    "262": "特殊産業用機械製造業",
    "270": "業務用機械器具製造業",
    "271": "事務用・サービス用機械器具製造業",
    "273": "計量器・測定器・分析機器・試験機・測量機製造業",
    "274": "医療用機械器具・医療用品製造業",
    "275": "光学機械器具・レンズ製造業",
    "276": "武器製造業",
    "280": "電子部品・デバイス・電子回路製造業",
    "290": "電気機械器具製造業",
    "291": "産業用電気機械器具製造業",
    "292": "民生用電気機械器具製造業",
    "293": "電子応用装置製造業",
    "299": "その他の電気機械器具製造業",
    "300": "情報通信機械器具製造業",
    "301": "通信機械器具・同関連機械器具製造業",
    "302": "電子計算機・同附属装置製造業",
    "310": "輸送用機械器具製造業",
    "311": "自動車・同附属品製造業",
    "319": "その他の輸送用機械器具製造業",
    "320": "その他の製造業",
    "F": "電気・ガス業",
    "331": "電気業",
    "341": "ガス業",
    "G": "情報通信業",
    "391": "ソフトウェア業",
    "392": "情報処理・提供サービス業",
    "401": "インターネット附随サービス業",
    "411": "映画・ビデオ制作業（※）",
    "413": "新聞業",
    "414": "出版業",
    "I1": "卸売業",
    "511": "繊維品卸売業",
    "512": "衣服・身の回り品卸売業",
    "521": "農畜産物・水産物卸売業",
    "522": "食料・飲料卸売業",
    "531": "建築材料卸売業",
    "532": "化学製品卸売業",
    "533": "石油・鉱物卸売業",
    "534": "鉄鋼製品卸売業",
    "535": "非鉄金属卸売業",
    "536": "再生資源卸売業",
    "541": "産業機械器具卸売業",
    "542": "自動車卸売業",
    "543": "電気機械器具卸売業",
    "549": "その他の機械器具卸売業",
    "551": "家具・建具・じゅう器等卸売業",
    "552": "医薬品・化粧品等卸売業",
    "553": "紙、紙製品卸売業",
    "559": "その他の卸売業",
    "I2": "小売業",
    "570": "織物・衣服・身の回り品小売業",
    "580": "飲食料品小売業",
    "591": "自動車・自転車小売業",
    "593": "機械器具小売業",
    "602": "家具・建具・じゅう器小売業",
    "603": "医薬品・化粧品小売業",
    "605": "燃料小売業",
    "609": "その他の小売業",
    "610": "無店舗小売業",
    "J1": "クレジットカード業、割賦金融業",
    "K1": "物品賃貸業",
    "702": "産業用機械器具賃貸業（レンタルを含む）",
    "703": "事務用機械器具賃貸業（レンタルを含む）",
    "704": "自動車賃貸業（レンタルを除く）",
    "708": "その他の物品賃貸業（レンタルを含む）",
    "L": "学術研究、専門・技術サービス業",
    "710": "学術・開発研究機関",
    "726": "デザイン業",
    "728": "エンジニアリング業",
    "730": "広告業",
    "743": "機械設計業",
    "744": "商品・非破壊検査業",
    "745": "計量証明業",
    "746": "写真業",
    "M": "飲食サービス業",
    "760": "一般飲食店",
    "770": "持ち帰り・配達飲食サービス業",
    "N": "生活関連サービス業、娯楽業",
    "781": "洗濯業",
    "789": "その他の洗濯・理容・美容業・浴場業",
    "796": "冠婚葬祭業（冠婚葬祭互助会を含む）",
    "797": "写真プリント,現像・焼付業",
    "798": "その他の生活関連サービス業",
    "801": "映画館",
    "803": "ゴルフ場",
    "804": "スポーツ施設提供業（809に該当するものを除く）",
    "805": "公園、遊園地・テーマパーク",
    "O": "個人教授所",
    "R1": "サービス業（その他のサービス業を除く）",
    "880": "廃棄物処理業",
    "900": "機械等修理業",
    "911": "職業紹介業",
    "912": "労働者派遣業",
    "927": "ディスプレイ業",
    "928": "テレマーケティング業",
    "929": "その他の事業サービス業",
    "R2": "サービス業（その他のサービス業）",
    "Z": "その他の産業"
}

industryjptoen_dict = {
    "合計": "Total",
    "鉱業、採石業、砂利採取業": "Mining, Quarrying, and Gravel Extraction",
    "製造業": "Manufacturing",
    "食料品製造業": "Food Manufacturing",
    "畜産食料品製造業": "Livestock Food Manufacturing",
    "水産食料品製造業": "Fishery Food Manufacturing",           
    "精穀・製粉業": "Grain Milling",
    "その他の食料品製造業": "Other Food Manufacturing",
    "飲料・たばこ・飼料製造業": "Beverage, Tobacco, and Feed Manufacturing",
    "清涼飲料・酒類・茶・たばこ製造業": "Beverage, Alcoholic Beverages, Tea, and Tobacco Manufacturing",
    "飼料・有機質肥料製造業": "Feed and Organic Fertilizer Manufacturing",
    "繊維工業": "Textile Industry",
    "製糸，紡績，ねん糸等製造業": "Silk, Spinning, and Yarn Manufacturing",
    "織物・ニット生地製造業": "Fabric and Knit Fabric Manufacturing",
    "染色整理業": "Dyeing and Finishing",
    "その他の繊維工業": "Other Textile Industries",
    "織物・ニット製衣服製造業": "Woven and Knit Clothing Manufacturing",
    "身の回り品・その他の繊維製品製造業": "Personal Items and Other Textile Products Manufacturing",
    "木材・木製品製造業（家具を除く）": "Wood and Wood Products Manufacturing (Excluding Furniture)",
    "製材・合板製造業": "Lumber and Plywood Manufacturing",
    "その他の木製品製造業（家具を除く）": "Other Wood Products Manufacturing (Excluding Furniture)",
    "家具・装備品製造業": "Furniture and Fixtures Manufacturing",
    "パルプ・紙・紙加工品製造業": "Pulp, Paper, and Paper Products Manufacturing",
    "パルプ・紙製造業": "Pulp and Paper Manufacturing",
    "紙加工品製造業": "Paper Product Manufacturing",
    "印刷・同関連業": "Printing and Related Activities",
    "化学工業": "Chemical Industry",
    "化学肥料・無機化学工業製品製造業": "Chemical Fertilizer and Inorganic Chemical Products Manufacturing",
    "有機化学工業製品製造業": "Organic Chemical Products Manufacturing",
    "油脂加工製品・石けん・合成洗剤・界面活性剤・塗料製造業": "Fat and Oil Processing, Soap, Synthetic Detergents, Surfactants, and Paint Manufacturing",
    "医薬品製造業": "Pharmaceutical Manufacturing",
    "その他の化学工業製品製造業": "Other Chemical Products Manufacturing",
    "石油製品・石炭製品製造業": "Petroleum and Coal Products Manufacturing",
    "石油精製業": "Petroleum Refining",
    "その他の石油製品・石炭製品製造業": "Other Petroleum and Coal Products Manufacturing",
    "プラスチック製品製造業": "Plastic Products Manufacturing",
    "ゴム製品製造業": "Rubber Products Manufacturing",
    "タイヤ・チューブ製造業": "Tire and Tube Manufacturing",
    "その他のゴム製品製造業": "Other Rubber Products Manufacturing",
    "なめし革・同製品・毛皮製造業": "Leather Tanning, Products, and Fur Manufacturing",
    "窯業・土石製品製造業": "Ceramics and Stone Products Manufacturing",
    "ガラス・同製品製造業": "Glass and Glass Products Manufacturing",
    "セメント・同製品製造業": "Cement and Cement Products Manufacturing",
    "その他の窯業・土石製品製造業": "Other Ceramics and Stone Products Manufacturing",
    "鉄鋼業": "Iron and Steel Industry",
    "銑鉄・粗鋼・鋼材製造業": "Pig Iron, Crude Steel, and Steel Products Manufacturing",
    "鋳鍛造品・その他の鉄鋼製品製造業": "Cast and Forged Products, and Other Steel Products Manufacturing",
    "非鉄金属製造業": "Non-Ferrous Metal Manufacturing",
    "非鉄金属製錬・精製業": "Non-Ferrous Metal Smelting and Refining",
    "非鉄金属加工品製造業": "Non-Ferrous Metal Fabricated Products Manufacturing",
    "金属製品製造業": "Metal Products Manufacturing",
    "建設用・建築用金属製品製造業": "Construction and Building Metal Products Manufacturing",
    "その他の金属製品製造業": "Other Metal Products Manufacturing",
    "はん用機械器具製造業": "General Purpose Machinery Manufacturing",
    "ボイラ・原動機製造業": "Boiler and Prime Mover Manufacturing",
    "ポンプ・圧縮機器製造業": "Pump and Compressor Manufacturing",
    "一般産業用機械・装置製造業": "General Industrial Machinery and Equipment Manufacturing",
    "その他のはん用機械・同部品製造業": "Other General Purpose Machinery and Parts Manufacturing",
    "生産用機械器具製造業": "Production Machinery and Equipment Manufacturing",
    "金属加工機械製造業": "Metalworking Machinery Manufacturing",
    "特殊産業用機械製造業": "Specialized Industrial Machinery Manufacturing",
    "業務用機械器具製造業": "Business Machinery and Equipment Manufacturing",
    "事務用・サービス用機械器具製造業": "Office and Service Machinery and Equipment Manufacturing",
    "計量器・測定器・分析機器・試験機・測量機製造業": "Measuring, Testing, and Surveying Equipment Manufacturing",
    "医療用機械器具・医療用品製造業": "Medical Machinery and Equipment Manufacturing",
    "光学機械器具・レンズ製造業": "Optical Instruments and Lens Manufacturing",
    "武器製造業": "Arms Manufacturing",
    "電子部品・デバイス・電子回路製造業": "Electronic Components, Devices, and Circuits Manufacturing",
    "電気機械器具製造業": "Electrical Machinery and Equipment Manufacturing",
    "産業用電気機械器具製造業": "Industrial Electrical Machinery and Equipment Manufacturing",
    "民生用電気機械器具製造業": "Consumer Electrical Machinery and Equipment Manufacturing",
    "電子応用装置製造業": "Electronic Application Equipment Manufacturing",
    "その他の電気機械器具製造業": "Other Electrical Machinery and Equipment Manufacturing",
    "情報通信機械器具製造業": "Information and Communication Machinery and Equipment Manufacturing",
    "通信機械器具・同関連機械器具製造業": "Communication Machinery and Related Equipment Manufacturing",
    "電子計算機・同附属装置製造業": "Computers and Peripheral Equipment Manufacturing",
    "輸送用機械器具製造業": "Transport Machinery and Equipment Manufacturing",
    "自動車・同附属品製造業": "Automobile and Parts Manufacturing",
    "その他の輸送用機械器具製造業": "Other Transport Machinery and Equipment Manufacturing",
    "その他の製造業": "Other Manufacturing",
    "電気・ガス業": "Electricity and Gas Industry",
    "電気業": "Electric Power Industry",
    "ガス業": "Gas Industry",
    "情報通信業": "Information and Communication Industry",
    "ソフトウェア業": "Software Industry",
    "情報処理・提供サービス業": "Information Processing and Provision Services",
    "インターネット附随サービス業": "Internet-Related Services",
    "映画・ビデオ制作業（※）": "Film and Video Production",
    "新聞業": "Newspaper Industry",
    "出版業": "Publishing Industry",
    "卸売業": "Wholesale Trade",
    "繊維品卸売業": "Textile Wholesale Trade",
    "衣服・身の回り品卸売業": "Clothing and Personal Items Wholesale Trade",
    "農畜産物・水産物卸売業": "Agricultural, Livestock, and Fishery Products Wholesale Trade",
    "食料・飲料卸売業": "Food and Beverage Wholesale Trade",
    "建築材料卸売業": "Building Materials Wholesale Trade",
    "化学製品卸売業": "Chemical Products Wholesale Trade",
    "石油・鉱物卸売業": "Petroleum and Mineral Wholesale Trade",
    "鉄鋼製品卸売業": "Steel Products Wholesale Trade",
    "非鉄金属卸売業": "Non-Ferrous Metals Wholesale Trade",
    "再生資源卸売業": "Recycled Materials Wholesale Trade",
    "産業機械器具卸売業": "Industrial Machinery and Equipment Wholesale Trade",
    "自動車卸売業": "Automobile Wholesale Trade",
    "電気機械器具卸売業": "Electrical Machinery and Equipment Wholesale Trade",
    "その他の機械器具卸売業": "Other Machinery and Equipment Wholesale Trade",
    "家具・建具・じゅう器等卸売業": "Furniture, Fixtures, and Household Goods Wholesale Trade",
    "医薬品・化粧品等卸売業": "Pharmaceuticals and Cosmetics Wholesale Trade",
    "紙、紙製品卸売業": "Paper and Paper Products Wholesale Trade",
    "その他の卸売業": "Other Wholesale Trade",
    "小売業": "Retail Trade",
    "織物・衣服・身の回り品小売業": "Textiles, Clothing, and Personal Items Retail Trade",
    "飲食料品小売業": "Food and Beverage Retail Trade",
    "自動車・自転車小売業": "Automobile and Bicycle Retail Trade",
    "機械器具小売業": "Machinery and Equipment Retail Trade",
    "家具・建具・じゅう器小売業": "Furniture, Fixtures, and Household Goods Retail Trade",
    "医薬品・化粧品小売業": "Pharmaceuticals and Cosmetics Retail Trade",
    "燃料小売業": "Fuel Retail Trade",
    "その他の小売業": "Other Retail Trade",
    "無店舗小売業": "Non-Store Retail Trade",
    "クレジットカード業、割賦金融業": "Credit Card and Installment Finance",
    "物品賃貸業": "Goods Rental and Leasing",
    "産業用機械器具賃貸業（レンタルを含む）": "Industrial Machinery and Equipment Rental (Including Leasing)",
    "事務用機械器具賃貸業（レンタルを含む）": "Office Machinery and Equipment Rental (Including Leasing)",
    "自動車賃貸業（レンタルを除く）": "Automobile Rental (Excluding Leasing)",
    "その他の物品賃貸業（レンタルを含む）": "Other Goods Rental (Including Leasing)",
    "学術研究、専門・技術サービス業": "Academic Research, Professional, and Technical Services",
    "学術・開発研究機関": "Academic and Development Research Institutions",
    "デザイン業": "Design Services",
    "エンジニアリング業": "Engineering Services",
    "広告業": "Advertising Industry",
    "機械設計業": "Mechanical Design Services",
    "商品・非破壊検査業": "Product and Non-Destructive Testing Services",
    "計量証明業": "Measurement Certification Services",
    "写真業": "Photography Services",
    "飲食サービス業": "Food and Beverage Services",
    "一般飲食店": "General Restaurants",
    "持ち帰り・配達飲食サービス業": "Takeout and Delivery Food Services",
    "生活関連サービス業、娯楽業": "Life-Related Services and Entertainment",
    "洗濯業": "Laundry Services",
    "その他の洗濯・理容・美容業・浴場業": "Other Laundry, Barber, Beauty, and Bath Services",
    "冠婚葬祭業（冠婚葬祭互助会を含む）": "Ceremonial Services (Including Mutual Aid Associations)",
    "写真プリント,現像・焼付業": "Photo Printing, Development, and Printing Services",
    "その他の生活関連サービス業": "Other Life-Related Services",
    "映画館": "Cinemas",
    "ゴルフ場": "Golf Courses",
    "スポーツ施設提供業（809に該当するものを除く）": "Sports Facility Provision (Excluding 809)",
    "公園、遊園地・テーマパーク": "Parks, Amusement Parks, and Theme Parks",
    "個人教授所": "Private Tutoring Institutions",
    "サービス業（その他のサービス業を除く）": "Service Industry (Excluding Other Services)",
    "廃棄物処理業": "Waste Management Services",
    "機械等修理業": "Machinery and Equipment Repair Services",
    "職業紹介業": "Employment Placement Services",
    "労働者派遣業": "Worker Dispatch Services",
    "ディスプレイ業": "Display Services",
    "テレマーケティング業": "Telemarketing Services",
    "その他の事業サービス業": "Other Business Services",
    "サービス業（その他のサービス業）": "Service Industry (Other Services)",
    "その他の産業": "Other Industries"
}

def get_industries_name(industry_id):
    return id2industries_dict.get(industry_id, "Unknown Industry")

def get_industries_id(industry_name):
    industry_name = industry_name.strip()
    # if first three characters are digits, return the id directly
    if industry_name[:3].isdigit():
        return industry_name[:3]
    for id, name in id2industries_dict.items():
        if name == industry_name:
            return id
    for id, name in id2industries_dict.items():
        if industry_name[1:-1] in name:
            return id
    return "Unknown Industry ID"